### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by IgorPropisnov** [taniarascia/webpack-boilerplate#16] opened 2020-10-28 21:33 UTC
Hi @taniarascia,

Thank you for your Project.

I have checked out the actual master branch and installed all dependencies. Afterward, I started the project with npm start.
The hot module reloader does not react to changes to the JS files, SCSS files, and HTML files.

**Comment by tpkahlon** [comment] 2020-10-29 00:29
@IgorPropisnov I followed your steps as mentioned above. It works on my end. Make sure `Node` and `npm` on your machine are up-to-date.

**Comment by taniarascia** [comment] 2020-10-29 14:32
Need more information about your setup. It works for me on macOS and Nod 14.4.

**Comment by IgorPropisnov** [comment] 2020-10-29 15:00
@tpkahlon I will try to update everything to the latest version. 
@taniarascia If it does not work then I will come back with more information

**Comment by IgorPropisnov** [comment] 2020-10-29 15:11
@tpkahlon updating to latest node LTS version 14.15.0 worked thanks. @taniarascia The HTML files are only updated after a manual page refresh. Is there a solution for this?

**Comment by taniarascia** [comment] 2020-10-29 15:12
That is intended. You can see https://github.com/taniarascia/webpack-boilerplate/pull/17 for a workaround, but I don't intend to support this in the boilerplate.

**Comment by IgorPropisnov** [comment] 2020-10-29 17:07
@taniarascia I tried the whole setup on Windows 10. Unfortunately no hot reload to scss or javascript file here.

Setup:
node.js version 14.15.0

Log after npm start
```
(node:4861) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'w
atch' option without a callback.
(Use `node --trace-deprecation ...` to show where the warning was created)
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /mnt/e/Projects/demo/webpack-boilerplate/dist
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: wait until bundle finished: /
ℹ ｢wdm｣: asset main.bundle.js 1.36 MiB [emitted] (name: main)
asset assets/example.jpg 92.3 KiB [emitted] [copied]
asset favicon.png 39 KiB [emitted]
asset index.html 394 bytes [emitted]
runtime modules 24.8 KiB 13 modules
modules by path ./node_modules/ 341 KiB
  modules by path ./node_modules/webpack-dev-server/client/ 20.9 KiB 10 modules
  modules by path ./node_modules/html-entities/lib/*.js 57.9 KiB 4 modules
  modules by path ./node_modules/webpack/hot/ 1.58 KiB 3 modules
  modules by path ./node_modules/url/ 37.4 KiB 3 modules
  modules by path ./node_modules/css-loader/dist/runtime/*.js 4.59 KiB 3 modules
  modules by path ./node_modules/querystring/*.js 4.51 KiB 3 modules
modules by path ./src/ 385 KiB
  javascript modules 5.02 KiB
    modules by path ./src/styles/*.scss 4.42 KiB 2 modules
    2 modules
  asset modules 380 KiB
    ./src/images/webpack-logo.svg 3.17 KiB [built] [code generated]
    ./src/fonts/Inter.ttf 377 KiB [built] [code generated]
webpack 5.1.3 compiled successfully in 67883 ms
ℹ ｢wdm｣: Compiled successfully.
```

**Comment by tpkahlon** [comment] 2020-10-29 17:21
@IgorPropisnov I tried #17 on my Windows machine but seems to work fine. I would recommend using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) for handling command line work in Windows. It provides you UNIX access similar to Mac so you won't need to spend any time on Node/NPM related configuration issues, you may run into.

**Comment by IgorPropisnov** [comment] 2020-10-29 17:45
@tpkahlon I already use wls2. I also have nvm running for node version managment. Can you tell me your project setup in detail?

**Comment by tpkahlon** [comment] 2020-10-29 19:00
@IgorPropisnov, please see details below:
Repository: [Link](https://github.com/tpkahlon/webpack-boilerplate.git)
Node: v14.9
npm: v6.14
WSL: Ubuntu for Windows 10

**Comment by 5ulo** [comment] 2020-10-29 19:42
Node 14.4.0
MacOs
npm 6.14.5
HMR is working for js/scss. Not working for html

**Comment by taniarascia** [comment] 2020-10-29 19:48
@5ulo 

> That is intended. You can see #17 for a workaround, but I don't intend to support this in the boilerplate.

**Comment by tpkahlon** [comment] 2020-10-29 20:54
To add onto @taniarascia's comment, if someone want to fork this project as a playground to test things in CSS/JS/HTML, they may feel the need to have multiple HTML files. You can do that using [this approach](https://github.com/jantimon/html-webpack-plugin#generating-multiple-html-files). In order to make your code easier to read, you can create a separate file to hold declaration of all your HTML files and then import that in `webpack.common.js`.

**Comment by cgomm** [comment] 2020-10-29 21:00
Hey there, i got the same Problem here, i am using WSL 2 (Ubuntu) using git, npm and node within. I got the same versions like @IgorPropisnov.

**Comment by Khwarazmi** [comment] 2020-10-30 01:18
I'm just confused how I'm supposed to see my development progress ?
i have to npm start each time i add anything to my files ? 

since npm start doesn't refresh anything how can i work like that ?
can someone guide me on the process?

i just wanted to see what i'm updating or doing, like if i added an image changed a color added something to my js, how can i see my live progress instead of running npm start each time,

i'm using ubuntu 20.04 on windows subsystem for linux

npm start opens the file but nothing is updating at all

**Comment by taniarascia** [comment] 2020-10-30 22:50
I'm not sure what the issue is. It appears this is not working for some users of Windows/WSL. I don't have a Windows PC to test this on. You shouldn't have to run `npm start` each time, every change to JS or SCSS should be updated automatically. If you also want to support changes to HTML you can add on #17.

**Comment by tpkahlon** [comment] 2020-10-30 23:54
@taniarascia I tested the boilerplate on Windows with/without WSL. It seems to work fine on my end. I did attach a screencast in thread above. IMO, you can close the issue.

**Comment by Khwarazmi** [comment] 2020-10-30 23:58
@taniarascia Thank you so much tania for your efforts it's working fine after adding
```
    watchOptions: {
      ignored: /node_modules/,
      poll: true
    }
```

**Comment by taniarascia** [comment] 2020-10-31 00:06
@tpkahlon Thanks for your help with this!

**Closed by taniarascia** 2020-10-31 00:06 UTC
