### ISSUE TITLE
Missing html-loader (cannot directly add an img in the .html)

### ISSUE THREAD

**Issue by brauliodiez** [taniarascia/webpack-boilerplate#26] opened 2020-11-05 15:47 UTC
If you try to add an image directly to the HTML it won't be processed by webpack and won't be displayed, for instance you can add the following to your template.html file

_./src/template.html_

```diff
  <body>
    <div id="root"></div>
    <img src="./images/webpack-logo.svg" />
  </body>
```

When it runs it should display to webpack logos, but you get this (if you scroll down):

![Screenshot 2020-11-05 at 16 45 17](https://user-images.githubusercontent.com/1457912/98262872-67a6de80-1f86-11eb-990c-ffa8e2267781.png)

I think it would be a good idea to add _html-loader_ to the boiler plate config. 

I'm going to raise a pull request pointing the possible solution

**Comment by tpkahlon** [comment] 2020-11-05 16:38
Duplicate of #22 and #16.

**Closed** 2020-12-11 21:41 UTC
