### ISSUE TITLE
nothing is reloading on wsl2

### ISSUE THREAD

**Issue by Khwarazmi** [taniarascia/webpack-boilerplate#21] opened 2020-10-30 21:51 UTC
I'm using wsl2 on windows 10 npm start doesn't change anything scripts, styles, html nothing is reloading, i was reading that this is intended not to reload just for the html files
can you guide me through possible fixes ? 

node v14.15.0
npm v6.14.8

+ i've tried node v15 same issue

**Comment by taniarascia** [comment] 2020-10-30 22:49
Duplicate of https://github.com/taniarascia/webpack-boilerplate/issues/16.

**Closed by taniarascia** 2020-10-30 22:49 UTC
